### PR TITLE
Better ingress error message on permission denied

### LINKED ISSUE #1631: Better ingress error message on pubsub authentication problem
**Describe the bug**

On pubsub authentication failure, the ingress nowadays just returns 500 with plain pubsub authentication error. 

 **Expected behavior**
We want to provide additional context to the error message. E.g. Pointer to the init/setup doc.

 **To Reproduce**
Use broker without going through init setup

### PR DESCRIPTION
**Pull request by cathyzhyi**
Fixes #1631 

## Proposed Changes

-
-
-

**Release Note**

```release-note
Provide additional error info when auth with pubsub fails in broker ingress.
```

**Docs**

### CODE REVIEW

File: pkg/broker/ingress/handler.go [hunk 1]
```diff
@@ -158,10 +160,18 @@ func (h *Handler) ServeHTTP(response nethttp.ResponseWriter, request *nethttp.Re
...
+		switch {
+		case errors.Is(res, ErrNotFound):
 			statusCode = nethttp.StatusNotFound
-		} else if errors.Is(res, ErrNotReady) {
+		case errors.Is(res, ErrNotReady):
 			statusCode = nethttp.StatusServiceUnavailable
+		case grpcstatus.Code(res) == grpccode.PermissionDenied:
+			const msg string = "Failed to publish to PubSub because permission denied.\n" +
+			"Please refer to \"Configure the Authentication Mechanism for GCP\" at " +
+			"https://github.com/google/knative-gcp/blob/master/docs/install/install-knative-gcp.md"
```
Comment (grac3gao) [inline pkg/broker/ingress/handler.go:172]: It might be better to point broker installation page(https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md) rather than install knative-gcp page (this is for the Control Plane setup)

Comment (cathyzhyi) [reply pkg/broker/ingress/handler.go]: Thanks Grace! Modified accordingly.

File: pkg/broker/ingress/handler.go [hunk 2]
```diff
@@ -158,10 +160,18 @@ func (h *Handler) ServeHTTP(response nethttp.ResponseWriter, request *nethttp.Re
...
+		switch {
+		case errors.Is(res, ErrNotFound):
 			statusCode = nethttp.StatusNotFound
-		} else if errors.Is(res, ErrNotReady) {
+		case errors.Is(res, ErrNotReady):
 			statusCode = nethttp.StatusServiceUnavailable
+		case grpcstatus.Code(res) == grpccode.PermissionDenied:
+			const msg string = "Failed to publish to PubSub because permission denied.\n" +
+				"Please refer to \"Configure the Authentication Mechanism for GCP\" at " +
+				"https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md"
```
Comment (yolocs) [inline pkg/broker/ingress/handler.go:172]: At the top you can define a constant like

```
const deniedErrMsg string = `Failed to publish to PubSub because permission denied.
Please refer to "Configure the Authentication Mechanism for GCP" at https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md
`
```

And use it here.

File: pkg/broker/ingress/handler.go [hunk 3]
```diff
@@ -158,10 +160,18 @@ func (h *Handler) ServeHTTP(response nethttp.ResponseWriter, request *nethttp.Re
...
-		if errors.Is(res, ErrNotFound) {
+
+		switch {
+		case errors.Is(res, ErrNotFound):
 			statusCode = nethttp.StatusNotFound
-		} else if errors.Is(res, ErrNotReady) {
+		case errors.Is(res, ErrNotReady):
 			statusCode = nethttp.StatusServiceUnavailable
+		case grpcstatus.Code(res) == grpccode.PermissionDenied:
+			const msg string = "Failed to publish to PubSub because permission denied.\n" +
```
Comment (yolocs) [inline pkg/broker/ingress/handler.go:170]: Also add a TODO. I think eventually we want to put a link to the official doc rather than github doc.

File: pkg/broker/ingress/handler.go [hunk 4]
```diff
@@ -158,10 +160,18 @@ func (h *Handler) ServeHTTP(response nethttp.ResponseWriter, request *nethttp.Re
...
 		statusCode = nethttp.StatusInternalServerError
-		if errors.Is(res, ErrNotFound) {
+
+		switch {
+		case errors.Is(res, ErrNotFound):
 			statusCode = nethttp.StatusNotFound
-		} else if errors.Is(res, ErrNotReady) {
+		case errors.Is(res, ErrNotReady):
 			statusCode = nethttp.StatusServiceUnavailable
+		case grpcstatus.Code(res) == grpccode.PermissionDenied:
```
Comment (yolocs) [inline pkg/broker/ingress/handler.go:169]: Just to confirm. Have you verified this in a cluster?

**Comment by yolocs** [comment]
Since this has impact on user facing function, it's best to add a release note. I helped to add it for this PR.

File: pkg/broker/ingress/handler.go (hunk 4 above)
Comment (cathyzhyi) [reply pkg/broker/ingress/handler.go:169]: Yes, it works in the cluster.

File: pkg/broker/ingress/handler.go (hunk 3 above)
Comment (cathyzhyi) [reply pkg/broker/ingress/handler.go]: Added TODO. thanks for the suggestion!

File: pkg/broker/ingress/handler.go (hunk 2 above)
Comment (cathyzhyi) [reply pkg/broker/ingress/handler.go]: Moved the const string definition to the top of the file as suggested. Thanks!

**Review by yolocs — COMMENTED** [review]
/lgtm
/approve
