### PR TITLE
Fix the brokerCell UT to test broker targets config

### LINKED ISSUE #1326: Flaky Test - BrokerCell created successfully, broker targets config should be updated with broker and triggers
**Describe the bug**
[BrokerCell created successfully, broker targets config should be updated with broker and triggers](https://github.com/google/knative-gcp/blob/571ffebac6611e9b7ca98870a47001434c32cc6b/pkg/reconciler/brokercell/brokercell_test.go#L801) is flaky.

In particular, it asserts the binary data of the ConfigMap must match exactly, but often doesn't. That is because the binary data represents a proto. So while the two protos are logically equivalent, because we are comparing bytes, the serialization order of the maps is asserted. That serialization order is not guaranteed.

 **Expected behavior**
The test should consistently pass.

 **To Reproduce**
```shell
go test ./pkg/reconciler/brokercell/ -count 100
```

 **Additional context**
```
--- FAIL: TestAllCases (0.05s)
    --- FAIL: TestAllCases/BrokerCell_created_successfully,_broker_targets_config_should_be_updated_with_broker_and_triggers (0.01s)
        logger.go:130: 2020-06-23T11:53:39.751-0700     DEBUG   brokercell-controller   reconciler/reconciler.go:171    Creating stats reporter {"events.cloud.google.com/controller": "brokercell-controller"}
        brokercell_test.go:947: Unexpected create (-want, +got):   &v1.ConfigMap{
                TypeMeta:   v1.TypeMeta{},
                ObjectMeta: v1.ObjectMeta{Name: "test-brokercell-brokercell-broker-targets", Namespace: "testnamespace", Labels: map[string]string{"app": "cloud-run-events", "brokerCell": "test-brokercell", "role": "broker-targets"}, OwnerReferences: []v1.OwnerReference{{APIVersion: "internal.events.cloud.google.com/v1alpha1", Kind: "BrokerCell", Name: "test-brokercell", Controller: &true, BlockOwnerDeletion: &true}}},
                Data:       map[string]string{"targets.txt": `brokers:{key:"testnamespace/broker" value:{name:"broker" namespace:"testnamespace" decouple_queue:{topic:"cre-bkr_testnamespace_broker_" subscription:"cre-bkr_testnamespace_broker_"} targets:{key:"trigger1" value:{name:"trigger1" namespace:"testnamespace" broker:"broker" retry_queue:{topic:"cre-tgr_testnamespace_trigger1_" subscription:"cre-tgr_testnamespace_trigger1_"}}} targets:{key:"trigger2" value:{name:"trigger2" namespace:"testnamespace" broker:"broker" retry_queue:{topic:"cre-tgr_testnamespace_trigger2_" subscription:"cre-tgr_testnamespace_trigger2_"}}}}}`},
                BinaryData: map[string][]uint8{
                        "targets": {
                                ... // 94 identical bytes
                                0x74, 0x65, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x62, 0x72, //  |testnamespace_br|
                                0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x32, 0x71, 0x0a, 0x08, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, //  |oker_2q..trigger|
            -                   0x31,                                                                                           // -|1|
            +                   0x32,                                                                                           // +|2|
                                0x12, 0x65, 0x12, 0x08, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,                               //  |.e..trigger|
            -                   0x31,                                                                                           // -|1|
            +                   0x32,                                                                                           // +|2|
                                0x1a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, //  |..testnamespace"|
                                0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x3a, 0x42, 0x0a, 0x1f, 0x63, 0x72, 0x65, 0x2d, 0x74, //  |.broker:B..cre-t|
                                0x67, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, //  |gr_testnamespace|
                                0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,                                                 //  |_trigger|
            -                   0x31,                                                                                           // -|1|
            +                   0x32,                                                                                           // +|2|
                                0x5f, 0x12, 0x1f, 0x63, 0x72, 0x65, 0x2d, 0x74, 0x67, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x6e, //  |_..cre-tgr_testn|
                                0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, //  |amespace_trigger|
            -                   0x31,                                                                                           // -|1|
            +                   0x32,                                                                                           // +|2|
                                0x5f, 0x32, 0x71, 0x0a, 0x08, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,                         //  |_2q..trigger|
            -                   0x32,                                                                                           // -|2|
            +                   0x31,                                                                                           // +|1|
                                0x12, 0x65, 0x12, 0x08, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,                               //  |.e..trigger|
            -                   0x32,                                                                                           // -|2|
            +                   0x31,                                                                                           // +|1|
                                0x1a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, //  |..testnamespace"|
                                0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x3a, 0x42, 0x0a, 0x1f, 0x63, 0x72, 0x65, 0x2d, 0x74, //  |.broker:B..cre-t|
                                0x67, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, //  |gr_testnamespace|
                                0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,                                                 //  |_trigger|
            -                   0x32,                                                                                           // -|2|
            +                   0x31,                                                                                           // +|1|
                                0x5f, 0x12, 0x1f, 0x63, 0x72, 0x65, 0x2d, 0x74, 0x67, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x6e, //  |_..cre-tgr_testn|
                                0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, //  |amespace_trigger|
            -                   0x32,                                                                                           // -|2|
            +                   0x31,                                                                                           // +|1|
                                0x5f,                                                                                           //  |_|
                        },
                },
              }
{"level":"info","ts":1592938419.803597,"logger":"fallback","caller":"brokercell/reconciler.go:277","msg":"Returned an event","targetMethod":"ReconcileKind","event":"BrokerCell reconciled: \"testnamespace/test-brokercell\""}
{"level":"info","ts":1592938419.8547149,"logger":"fallback","caller":"brokercell/reconciler.go:277","msg":"Returned an event","targetMethod":"ReconcileKind","event":"BrokerCell reconciled: \"testnamespace/test-brokercell\""}
FAIL
FAIL    github.com/google/knative-gcp/pkg/reconciler/brokercell 5.309s
FAIL
```

### PR DESCRIPTION
**Pull request by danyinggu**
Fixes #1326 

## Proposed Changes

- 🐛  Fix the brokercell UT that when the brokercell creates successfully, the broker target config should be updated with broker and triggers
- Synced with Cong, since this test involves testing the binary data in the configMap, but the binary data are not guaranteed the serialization order, we need to deserialize the binary data back to the broker target config proto, so it should be rewritten to a stand-alone test case without utilizing the tableTest framework.

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

File: pkg/reconciler/brokercell/brokercell_test.go [hunk 1]
```diff
@@ -933,3 +906,64 @@ func emptyHPASpec(template *hpav2beta2.HorizontalPodAutoscaler) *hpav2beta2.Hori
...
+		triggerLister:    testingListers.GetTriggerLister(),
+		configMapLister:  testingListers.GetConfigMapLister(),
+		serviceLister:    testingListers.GetK8sServiceLister(),
+		endpointsLister:  testingListers.GetEndpointsLister(),
+		deploymentLister: testingListers.GetDeploymentLister(),
+		podLister:        testingListers.GetPodLister(),
+	}
+	r, err := NewReconciler(base, ls)
+	if err != nil {
+		t.Fatalf("Failed to created BrokerCell reconciler: %v", err)
```
Comment (liu-cong) [inline pkg/reconciler/brokercell/brokercell_test.go:939]:
```suggestion
		t.Fatalf("Failed to create BrokerCell reconciler: %v", err)
```

File: pkg/reconciler/brokercell/brokercell_test.go [hunk 2]
```diff
@@ -933,3 +906,64 @@ func emptyHPASpec(template *hpav2beta2.HorizontalPodAutoscaler) *hpav2beta2.Hori
...
+	}
+	// here we only want to test the functionality of the reconcileConfig that it should create a brokerTargets config successfully
+	r.reconcileConfig(ctx, bc)
+	wantMap := testingdata.Config(t, NewBrokerCell(brokerCellName, testNS, WithBrokerCellSetDefaults),
+		NewBroker("broker", testNS, WithBrokerSetDefaults),
+		NewTrigger("trigger1", testNS, "broker", WithTriggerSetDefaults),
+		NewTrigger("trigger2", testNS, "broker", WithTriggerSetDefaults))
+	mapList, err := client.CoreV1().ConfigMaps(testNS).List(metav1.ListOptions{})
```
Comment (liu-cong) [inline pkg/reconciler/brokercell/brokercell_test.go:947]: nit: Let's use Get instead of List

File: pkg/reconciler/brokercell/brokercell_test.go [hunk 3]
```diff
@@ -933,3 +906,64 @@ func emptyHPASpec(template *hpav2beta2.HorizontalPodAutoscaler) *hpav2beta2.Hori
...
+	if err != nil || len(mapList.Items) != 1 {
+		t.Fatalf("Failed to get configMap: %v", err)
+	}
+	gotMap := mapList.Items[0]
+	// compare the ObjectMeta field
+	if diff := cmp.Diff(wantMap.ObjectMeta, gotMap.ObjectMeta, cmpopts.EquateEmpty()); diff != "" {
```
Comment (liu-cong) [inline pkg/reconciler/brokercell/brokercell_test.go:953]: nit: probably don't need the `EquateEmpty`

File: pkg/reconciler/brokercell/brokercell_test.go [hunk 4]
```diff
@@ -933,3 +906,64 @@ func emptyHPASpec(template *hpav2beta2.HorizontalPodAutoscaler) *hpav2beta2.Hori
...
+	var wantBrokerTargets config.TargetsConfig
+	var gotBrokerTargets config.TargetsConfig
+	if err := proto.Unmarshal(wantMap.BinaryData[targetsCMKey], &wantBrokerTargets); err != nil {
+		t.Fatalf("Failed to deserialize the binary data in configMap: %v", err)
+	}
+	if err := proto.Unmarshal(gotMap.BinaryData[targetsCMKey], &gotBrokerTargets); err != nil {
+		t.Fatalf("Failed to deserialize the binary data in configMap: %v", err)
+	}
+	// compare the broker targets config
+	if diff := cmp.Diff(wantBrokerTargets.String(), gotBrokerTargets.String(), cmpopts.EquateEmpty()); diff != "" {
```
Comment (liu-cong) [inline pkg/reconciler/brokercell/brokercell_test.go:966]: Have you verified that `String()` maintains the order of the map? I would expect cmp.Diff(wantBrokerTargets, gotBrokerTargets) should do the trick.

Comment (danyinggu) [reply pkg/reconciler/brokercell/brokercell_test.go:966]: Yeah, the `String()` maintains the order, as I rerun the fixed test 100 times and they all passed. I tried to compare the targetsConfig type directly but got this error, ```panic: cannot handle unexported field at {config.TargetsConfig}.state:
	"github.com/google/knative-gcp/pkg/broker/config".TargetsConfig
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported [recovered]
```. It even happens after I added AllowUnexported and cmpopts.IgnoreUnexported as comparison option.

File: pkg/reconciler/brokercell/brokercell_test.go [hunk 5]
```diff
@@ -935,3 +909,60 @@ func emptyHPASpec(template *hpav2beta2.HorizontalPodAutoscaler) *hpav2beta2.Hori
...
+	if err != nil {
+		t.Fatalf("Failed to create BrokerCell reconciler: %v", err)
+	}
+	// here we only want to test the functionality of the reconcileConfig that it should create a brokerTargets config successfully
+	r.reconcileConfig(ctx, bc)
+	wantMap := testingdata.Config(t, NewBrokerCell(brokerCellName, testNS, WithBrokerCellSetDefaults),
+		NewBroker("broker", testNS, WithBrokerSetDefaults),
+		NewTrigger("trigger1", testNS, "broker", WithTriggerSetDefaults),
+		NewTrigger("trigger2", testNS, "broker", WithTriggerSetDefaults))
+	gotMap, err := client.CoreV1().ConfigMaps(testNS).Get(resources.Name(bc.Name, targetsCMName),metav1.GetOptions{})
```
Comment (liu-cong) [inline pkg/reconciler/brokercell/brokercell_test.go:950]: nit: check the err and fatal

File: pkg/reconciler/brokercell/brokercell_test.go (hunk 4 above)
Comment (danyinggu) [reply pkg/reconciler/brokercell/brokercell_test.go]: I tried `proto.Equals()` and it works. The concerns is that this function only returns the boolean type, so I guess cmp.Diff() would be better when the two proto not matches as it will show the detailed diff?
