### PR TITLE
fixed the PullSubscriptions do not recover from Topic deletion 

### LINKED ISSUE #997: PullSubscriptions do not recover from Topic deletion
**Describe the bug**
When a `Topic` is deleted, all `PullSubscriptions` pointing to that Topic stop working, permanently. The `PullSubscription` is still marked as Ready=true, but it will not get any new events, ever (any still yet to be processed will still be sent).

 **Expected behavior**
Everything self-heals such that the higher level objects (e.g. `Channel` and `Broker`) work.

 **To Reproduce**
1. Create a PubSub `Channel` and a `Subscription` to that Channel. 
    `kubectl apply -f docs/examples/channel`
1. Wait for them to be Ready=true.
    `kubectl get channel demo`
    `kubectl get subscription demo`
1. Optional. Send an event to the Channel and see that it is sent to the subscriber.
    There is a PingSource pointed at the Channel already, so just wait at least one minute.
    `kubectl logs -l app=event-display`
1. Delete the Channel's `Topic`. 
    `kubectl delete topic cre-demo-chan`
1. See everything get back to Ready=true.
    `kubectl get channel demo`
    `kubectl get subscription demo`
1. Events sent to the Channel will not be sent to the subscriber.
     The PingSource is still sending events every minute, so just wait at least one minute. Notice that there will be no new log entries. 
    `kubectl logs -l app=event-display`
1. Optional. Add a new `Subscription` and see that events are sent to the new subscriber, but not the old one.

 **Additional context**
We likely need our `PullSubscription` reconciler to check the value returned by the GCP API. In particular, look at the PullSubscription's `topic` field. If it is `_deleted-topic_`, then realize there is more work to do.

This seems to be a property of the Pub/Sub API:

```shell
└─( 2 ) ❱❱❱ gcloud pubsub topics create my-topic
Created topic [projects/my-proj/topics/my-topic].

└─( 2 ) ❱❱❱ gcloud pubsub topics describe my-topic
messageStoragePolicy:
  allowedPersistenceRegions:
  - asia-east1
  - asia-northeast1
  - asia-southeast1
  - australia-southeast1
  - europe-north1
  - europe-west1
  - europe-west2
  - europe-west3
  - europe-west4
  - us-central1
  - us-central2
  - us-east1
  - us-east4
  - us-west1
  - us-west2
  - us-west3
  - us-west4
name: projects/my-proj/topics/my-topic

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions create my-sub --topic my-topic
Created subscription [projects/my-proj/subscriptions/my-sub].

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions describe my-sub
ackDeadlineSeconds: 10
expirationPolicy:
  ttl: 2678400s
messageRetentionDuration: 604800s
name: projects/my-proj/subscriptions/my-sub
pushConfig: {}
topic: projects/my-proj/topics/my-topic

└─( 2 ) ❱❱❱ gcloud pubsub topics delete my-topic
Deleted topic [projects/my-proj/topics/my-topic].

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions describe my-sub
ackDeadlineSeconds: 10
expirationPolicy:
  ttl: 2678400s
messageRetentionDuration: 604800s
name: projects/my-proj/subscriptions/my-sub
pushConfig: {}
topic: _deleted-topic_

└─( 2 ) ❱❱❱ gcloud pubsub topics create my-topic
Created topic [projects/my-proj/topics/my-topic].

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions describe my-sub
ackDeadlineSeconds: 10
expirationPolicy:
  ttl: 2678400s
messageRetentionDuration: 604800s
name: projects/my-proj/subscriptions/my-sub
pushConfig: {}
topic: _deleted-topic_
```

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #997 

## Proposed Changes

- 🐛 Channel and Source can recover from Topic Deletion

### CODE REVIEW

File: pkg/reconciler/intevents/pullsubscription/reconciler.go [hunk 1]
```diff
@@ -255,10 +278,7 @@ func (r *Base) deleteSubscription(ctx context.Context, ps *v1beta1.PullSubscript
 		return err
 	}
 	if exists {
-		if err := sub.Delete(ctx); err != nil {
-			logging.FromContext(ctx).Desugar().Error("Failed to delete Pub/Sub subscription", zap.Error(err))
-			return err
-		}
+		sub.Delete(ctx)
```
Comment (liu-cong) [inline pkg/reconciler/intevents/pullsubscription/reconciler.go]: What motivated this change?

File: pkg/reconciler/intevents/pullsubscription/reconciler.go [hunk 2]
```diff
@@ -217,9 +221,28 @@ func (r *Base) reconcileSubscription(ctx context.Context, ps *v1beta1.PullSubscr
 		subConfig.RetentionDuration = retentionDuration
 	}
 
-	// If the subscription doesn't exist, create it.
-	if !subExists {
-		// Create a new subscription to the previous topic with the given name.
+	// Check if the topic of the subscription is "_deleted-topic_"
+	if subExists {
```
Comment (liu-cong) [inline pkg/reconciler/intevents/pullsubscription/reconciler.go:225]: Can you add some unit tests for this (as a follow up PR)?
