### PR TITLE
fixed the bypass broker bug and modified the test framework of e2e te…

### LINKED ISSUE #1088: Fix the bypass broker bug in E2E tests
**Describe the bug**
Currently, for all E2E tests of sources with broker,
we set the sink of the source to be the kservice instead of the broker though we still set the sink url of the source to be broker.
Based on the logs of E2E tests, we really bypass the broker for all E2E tests of sources with broker.
[logs](https://storage.googleapis.com/knative-prow/pr-logs/pull/google_knative-gcp/1069/pull-google-knative-gcp-integration-tests/1261361030118772736/build-log.txt)
FYI:
 
TestCloudStorageSourceBrokerWithPubSubChannel: tracker.go:128: Cleaning resource: "storage-e2e-test-knative-boskos-08-storage-prslonku"
        {
          "apiVersion": "events.cloud.google.com/v1alpha1",
          "kind": "CloudStorageSource",
          "metadata": {
            "annotations": {
              "cluster-name": "fake-cluster-name"
            },
            "creationTimestamp": "2020-05-15T18:48:52Z",
            "finalizers": [
              "cloudstoragesources.events.cloud.google.com"
            ],
            "generation": 1,
            "name": "storage-e2e-test-knative-boskos-08-storage-prslonku",
            "namespace": "test-cloud-storage-source-broker-with-pub-sub-channel-v5zld",
            "resourceVersion": "17648",
            "selfLink": "/apis/events.cloud.google.com/v1alpha1/namespaces/test-cloud-storage-source-broker-with-pub-sub-channel-v5zld/cloudstoragesources/storage-e2e-test-knative-boskos-08-storage-prslonku",
            "uid": "c9507bc6-dae9-4f29-a9f2-cc3fe166d21e"
          },
          "spec": {
            "bucket": "storage-e2e-test-knative-boskos-08",
            "eventTypes": [
              "com.google.cloud.storage.object.finalize",
              "com.google.cloud.storage.object.delete",
              "com.google.cloud.storage.object.archive",
              "com.google.cloud.storage.object.metadataUpdate"
            ],
            "secret": {
              "key": "key.json",
              "name": "google-cloud-key"
            },
            **"sink": {
              "ref": {
                "apiVersion": "v1",
                "kind": "Service",
                "name": "storage-e2e-test-knative-boskos-08-target-icdpdysi"
              }**
            }
          },
          "status": {
            "conditions": [
              {
                "lastTransitionTime": "2020-05-15T18:50:04Z",
                "status": "True",
                "type": "NotificationReady"
              },
              {
                "lastTransitionTime": "2020-05-15T18:50:10Z",
                "status": "True",
                "type": "PullSubscriptionReady"
              },
              {
                "lastTransitionTime": "2020-05-15T18:50:10Z",
                "status": "True",
                "type": "Ready"
              },
              {
                "lastTransitionTime": "2020-05-15T18:50:00Z",
                "status": "True",
                "type": "TopicReady"
              }
            ],
            "notificationId": "238",
            "observedGeneration": 1,
            "projectId": "knative-boskos-08",
            **"sinkUri": "http://storage-e2e-test-knative-boskos-08-target-icdpdysi.test-cloud-storage-source-broker-with-pub-sub-channel-v5zld.svc.cluster.local/",**
            "topicId": "storage-c9507bc6-dae9-4f29-a9f2-cc3fe166d21e"
          }
        }

 **Expected behavior**
The sink and sink url of sources in E2E tests of sources with broker should point to the broker instead of the kservice.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #1088 

## Proposed Changes

- fixed the bypass broker bug
- modified the test framework of e2e tests related to sources with broker
- added receivers for all sources
- fixed some side effects when running all tests together
- renaming to get rid of magic string
- change the timeout of e2e-tests.sh to 30m

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by capri-xiyue** [comment]
It looks like we modified the framework of xxx_target.
I will resolve the merge conflicts later.
Besides the xxx_target, other parts are ready for review.

**Comment by capri-xiyue** [comment]
@liu-cong After I used the latest master, I hit the error `the server could not find the requested resource (post pullsubscriptions.internal.events.cloud.google.com)`you mentioned without setting GOOGLE_APPLICATION_CREDENTIALS when running E2E tests related to pullsubscription.

File: test/test_images/target/main.go [hunk 1]
```diff
@@ -25,56 +26,68 @@ func main() {
 		panic(err)
 	}
 
-	fmt.Printf("Target prefix to match: %q.\n", r.Target)
+
```
Comment (capri-xiyue) [inline test/test_images/target/main.go:29]: For this part, we have not used the framework used as that in other xxx_target, will change it later

File: test/test_images/pubsub_target/main.go [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+	"os"
+	"strconv"
+	"time"
+
+	cloudevents "github.com/cloudevents/sdk-go"
+	"github.com/google/knative-gcp/test/e2e/lib"
+	"github.com/kelseyhightower/envconfig"
+)
+
+func main() {
```
Comment (capri-xiyue) [inline test/test_images/pubsub_target/main.go:18]: This part doesn't use the test framework that other xxx_target use. Will change it later

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source.go [hunk 3]
```diff
@@ -235,65 +326,49 @@ func BrokerEventTransformationTestWithSchedulerSourceHelper(client *lib.Client,
...
-	client.Core.WaitForResourceReadyOrFail(kserviceName, lib.KsvcTypeMeta)
-	client.Core.WaitForResourcesReadyOrFail(eventingtestlib.TriggerTypeMeta)
-}
-
 func makeTargetJobOrDie(client *lib.Client, targetName string) {
 	client.T.Helper()
 	job := resources.TargetJob(targetName, []v1.EnvVar{{
-		Name:  "TARGET",
-		Value: "falldown",
+		Name:  "TIME",
```
Comment (nachocano) [inline test/e2e/lib/helpers/broker_event_transformation_test_with_source.go:370]: can we comment what this time is for?

File: test/e2e/lib/pubsub.go [hunk 4]
```diff
@@ -31,11 +33,11 @@ import (
 
 func MakePubSubOrDie(client *Client,
 	gvk metav1.GroupVersionKind,
```
Comment (nachocano) [inline test/e2e/lib/pubsub.go:35]: this is the gvk of the sink name? might be clearer to say sinkGVK

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source.go (hunk 3 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source.go:370]: `Time` will get deleted after I change the `target` to the test framework that other targets use like `storage_target`

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source.go [hunk 5]
```diff
@@ -89,36 +106,54 @@ func BrokerEventTransformationTestHelper(client *lib.Client, brokerURL url.URL,
...
 	topicName, deleteTopic := lib.MakeTopicOrDie(client.T)
 	defer deleteTopic()
 
 	psName := helpers.AppendRandomString(topicName + "-pubsub")
 	targetName := helpers.AppendRandomString(topicName + "-target")
+	data := fmt.Sprintf(`{"topic":%s}`, topicName)
+	source := v1alpha1.CloudPubSubSourceEventSource(project, topicName)
+
+	// Create a target PubSub Job to receive the events.
+	lib.MakePubSubTargetJobOrDie(client, source, targetName, lib.E2EPubSubRespEventType)
```
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source.go:119]: We use `job` as the `target`, but for `receiver` we use `ksvc`
                              5                   4
                    ------------------   --------------------
                    |                 | |                    |
          1         v	      2       | v         3          |
(Sender or Source) --->   Broker ---> trigger -------> Knative Service(Receiver)
                    |
                    |    6                   7
                    |-------> respTrigger -------> Service(Target)

File: test/e2e/lib/auditlogs.go [hunk 6]
```diff
@@ -60,7 +62,7 @@ func MakeAuditLogsJobOrDie(client *Client, methodName, project, resourceName, se
 		Value: resourceName,
 	}, {
 		Name:  "TYPE",
-		Value: v1alpha1.CloudAuditLogsSourceEvent,
+		Value: eventType,
```
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/lib/auditlogs.go:65]: Yep.
For source->target and source->broker->ksvc, they are different,
one use `v1alpha1.CloudAuditLogsSourceEvent`, the other use `lib.E2EAuditLogsRespType`.
To avoid the bug that we bypass the broker and don't check the reply events, I changed the type of the reply events to `lib.E2EAuditLogsRespType`, you can check the logic here https://github.com/capri-xiyue/knative-gcp/blob/536bbadd255c3f1c9c805b6b0b62b410e8ca3251/test/test_images/auditlogs_receiver/main.go#L60

File: test/e2e/lib/scheduler.go [hunk 7]
```diff
@@ -17,32 +17,32 @@ limitations under the License.
...
 	kngcpresources "github.com/google/knative-gcp/pkg/reconciler/events/scheduler/resources"
 	kngcptesting "github.com/google/knative-gcp/pkg/reconciler/testing"
 	"github.com/google/knative-gcp/test/e2e/lib/resources"
 	v1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
 func MakeSchedulerOrDie(client *Client,
-	sName, data, targetName, pubsubServiceAccount string,
+	gvk metav1.GroupVersionKind, schedulerName, data, sinkName, pubsubServiceAccount string,
```
Comment (nachocano) [inline test/e2e/lib/scheduler.go:28]: nit: same here, if gvk is for the sink, then I think we can call it sinkGVK

Comment (nachocano) [reply test/e2e/lib/scheduler.go:28]: same with others

File: test/e2e/test_auditlogs.go [hunk 8]
```diff
@@ -19,6 +19,7 @@ package e2e
 import (
 	"encoding/json"
 	"fmt"
+	"github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
```
Comment (nachocano) [inline test/e2e/test_auditlogs.go:22]: nit: importer

File: test/e2e/test_pubsub.go [hunk 9]
```diff
@@ -19,16 +19,17 @@ package e2e
 import (
 	"context"
 	"encoding/json"
+	"fmt"
+	"github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
```
Comment (nachocano) [inline test/e2e/test_pubsub.go:23]: nit: fomatter

File: test/e2e/test_pullsubscription.go [hunk 10]
```diff
@@ -19,19 +19,20 @@ package e2e
 import (
 	"context"
 	"encoding/json"
+	"fmt"
+	"github.com/google/knative-gcp/pkg/apis/events/v1beta1"
```
Comment (nachocano) [inline test/e2e/test_pullsubscription.go:23]: nit: importer

File: test/e2e/test_scheduler.go [hunk 11]
```diff
@@ -18,6 +18,8 @@ package e2e
 
 import (
 	"encoding/json"
+	"github.com/google/knative-gcp/pkg/apis/events/v1beta1"
```
Comment (nachocano) [inline test/e2e/test_scheduler.go:21]: same

File: test/e2e/test_storage.go [hunk 12]
```diff
@@ -19,6 +19,7 @@ package e2e
 import (
 	"context"
 	"encoding/json"
+	"github.com/google/knative-gcp/pkg/apis/events/v1beta1"
```
Comment (nachocano) [inline test/e2e/test_storage.go:22]: same

File: test/test_images/auditlogs_receiver/main.go [hunk 13]
```diff
@@ -0,0 +1,70 @@
+/*
+Copyright 2019 Google LLC
```
Comment (nachocano) [inline test/test_images/auditlogs_receiver/main.go:2]: nit: 2020

File: test/test_images/auditlogs_receiver/main.go [hunk 14]
```diff
@@ -0,0 +1,70 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package main
+
+import (
+	"context"
+	"github.com/google/knative-gcp/pkg/apis/events/v1beta1"
```
Comment (nachocano) [inline test/test_images/auditlogs_receiver/main.go:21]: formatter

File: test/test_images/pubsub_receiver/main.go [hunk 15]
```diff
@@ -0,0 +1,69 @@
+/*
+Copyright 2019 Google LLC
```
Comment (nachocano) [inline test/test_images/pubsub_receiver/main.go:2]: nit: 2020

File: test/test_images/pubsub_target/main.go [hunk 16]
```diff
@@ -0,0 +1,57 @@
+package main
```
Comment (nachocano) [inline test/test_images/pubsub_target/main.go:1]: add copyright?

File: test/test_images/pubsub_receiver/pod.yaml [hunk 17]
```diff
@@ -0,0 +1,9 @@
+apiVersion: v1
```
Comment (nachocano) [inline test/test_images/pubsub_receiver/pod.yaml:1]: I think I'd add copyright to the yamls as well

File: test/test_images/pubsub_target/main.go [hunk 18]
```diff
@@ -0,0 +1,57 @@
...
+
+type pubsubReceiver struct {
+	knockdown.Config
+	Type   string `envconfig:"TYPE" required:"true"`
+	Source string `envconfig:"SOURCE" required:"true"`
+}
+
+func (r *pubsubReceiver) Knockdown(event cloudevents.Event) bool {
+	// Print out event received to log
+	// Print out event received to log
```
Comment (nachocano) [inline test/test_images/pubsub_target/main.go:34]: duplicated comment

File: test/test_images/receiver/main.go [hunk 19]
```diff
@@ -18,6 +18,7 @@ package main
 
 import (
 	"context"
+	"github.com/google/knative-gcp/test/e2e/lib"
```
Comment (nachocano) [inline test/test_images/receiver/main.go:21]: nit: importer

File: test/test_images/scheduler_receiver/main.go [hunk 20]
```diff
@@ -0,0 +1,70 @@
+/*
+Copyright 2019 Google LLC
```
Comment (nachocano) [inline test/test_images/scheduler_receiver/main.go:2]: nit: 2020

Comment (nachocano) [reply test/test_images/scheduler_receiver/main.go:2]: wondering if we can pass in an ENV variable saying which source it is, and then just have one image, with an if, else if, else if, and so on... Seems that we are duplicating a bunch of main.go files, and we can just have one...
No need to do in this PR though... just a thought

File: test/test_images/sender/main.go [hunk 21]
```diff
@@ -20,6 +20,7 @@ import (
 	"context"
 	"encoding/json"
 	"fmt"
+	"github.com/google/knative-gcp/test/e2e/lib"
```
Comment (nachocano) [inline test/test_images/sender/main.go:23]: nit: formatter

File: test/test_images/storage_receiver/main.go [hunk 22]
```diff
@@ -0,0 +1,69 @@
+/*
+Copyright 2019 Google LLC
```
Comment (nachocano) [inline test/test_images/storage_receiver/main.go:2]: nit: 2020

File: test/test_images/storage_receiver/main.go [hunk 23]
```diff
@@ -0,0 +1,69 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package main
+
+import (
+	"context"
+	"github.com/google/knative-gcp/pkg/apis/events/v1beta1"
```
Comment (nachocano) [inline test/test_images/storage_receiver/main.go:21]: formatter

**Comment by nachocano** [comment]
@capri-xiyue made a pass. Mainly nits, let me know when it's ready for another review and I'll take a look. Thanks!

File: test/test_images/scheduler_receiver/main.go (hunk 20 above)
Comment (capri-xiyue) [reply test/test_images/scheduler_receiver/main.go:2]: Yep. We can try create another issue to investigate how to do that

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source.go [hunk 24]
```diff
@@ -63,7 +63,24 @@ func BrokerEventTransformationTestHelper(client *lib.Client, brokerURL url.URL,
...
+	createTriggerWithKServiceSubscriber(client, brokerName, kserviceName, triggerFilter)
+
+	// Create a Trigger with the target Service subscriber.
+	respTriggerFilter:=eventingtestresources.WithAttributesTriggerFilter(
+		eventingv1alpha1.TriggerAnyFilter, eventingv1alpha1.TriggerAnyFilter,
+		map[string]interface{}{"type": 	lib.E2EDummyRespEventType})
+	createTriggerWithTargetServiceSubscriber(client, brokerName, targetName, respTriggerFilter)
+
+	// Wait for ksvc, trigger ready.
+	client.Core.WaitForResourceReadyOrFail(kserviceName, lib.KsvcTypeMeta)
```
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source.go:82]: Yep. There is a WaitForResource**s**ReadyOrFail. 
But WaitForResource**s**ReadyOrFail also needs to specify `typemeta *metav1.TypeMeta`. Here we use WaitForResourceReadyOrFail is because we only have one ksvc.
For the triggers, we use WaitForResource**s**ReadyOrFail  because we have two triggers

**Comment by nachocano** [comment]
/lgtm
Thanks @capri-xiyue for doing this! Let's hope this improves the flakiness also
