### PR TITLE
Failures to send Replies are considered delivery failures

### LINKED ISSUE #2106: Broker does not inspect the response to replies
**Describe the bug**
When a Trigger replies with an event, that event is sent back to the Broker Ingress. However, our implementation does not inspect the response code of the request to the Broker Ingress, so an event can easily get lost.

 **Expected behavior**
If sending the reply to the Broker Ingress fails, then it either needs to be retried or the event needs to be processed by the Trigger again.

**Repro**
See the `reply server failure` unit test added in #2107, which has a TODO related to this issue.

### PR DESCRIPTION
**Pull request by Harwayne**
Fixes #2106.

## Proposed Changes

- If the reply event is not successfully delivered, then the overall event delivery via the Trigger is considered a failure.
- Add unit tests for successful replies.
- Fix `malformed CloudEvent reply failure` unit test, which passed for the wrong reason.

**Release Note**

```release-note
🐛 Failures to send a Trigger's reply back into the Broker are now retried.
```

### CODE REVIEW

File: pkg/broker/handler/processors/deliver/processor.go [hunk 1]
```diff
@@ -239,6 +239,9 @@ func (p *Processor) deliver(ctx context.Context, target *config.Target, broker *
 	if err != nil {
 		return err
 	}
+	if replyResp.StatusCode/100 != 2 {
```
Comment (Harwayne) [inline pkg/broker/handler/processors/deliver/processor.go:242]: We should probably add some metrics around these replies too...

Comment (zhongduo) [reply pkg/broker/handler/processors/deliver/processor.go:242]: More metrics is already better. Can we change this to sth like `replyResp.StatusCode >= 200 && replyResp.StatusCode < 300`, I found this easier to process and it is also faster for the CPU.

File: pkg/broker/handler/processors/deliver/processor_test.go [hunk 2]
```diff
@@ -235,16 +246,33 @@ func (h *targetWithFailureHandler) ServeHTTP(w http.ResponseWriter, req *http.Re
...
 		// Content-Type does not start with `application/cloudevents`
 		w.Header().Set("Content-Type", "text/html")
+	} else if h.structuredContentMode {
+		w.Header().Set("Content-Type", "application/cloudevents+json; charset=utf-8")
 	}
 	w.WriteHeader(h.respCode)
 	w.Write([]byte(h.respBody))
 }
 
+type testingReplyHandler struct {
```
Comment (zhongduo) [inline pkg/broker/handler/processors/deliver/processor_test.go:256]: Reply seems too generic for understanding, maybe change to sth like `brokerReplyHandler` or `brokerIngressReplyHandler`.

File: pkg/broker/handler/processors/deliver/processor_test.go [hunk 3]
```diff
@@ -58,6 +58,16 @@ import (
 const (
 	fakeTargetAddress  = "target"
 	fakeIngressAddress = "ingress"
+	ceBody             = `{
+  "specversion": "1.0",
+  "type": "com.exmaple.someevent",
```
Comment (tayarani) [inline pkg/broker/handler/processors/deliver/processor_test.go:63]: typo: exmaple

**Comment by zhongduo** [comment]
I hope the conformance test can capture it some day.

File: pkg/broker/handler/processors/deliver/processor.go (hunk 1 above)
Comment (Harwayne) [reply pkg/broker/handler/processors/deliver/processor.go:242]: Added a TODO, making this metrics is a much larger change.

File: pkg/broker/handler/processors/deliver/processor_test.go (hunk 3 above)
Comment (Harwayne) [reply pkg/broker/handler/processors/deliver/processor_test.go:63]: Done.

File: pkg/broker/handler/processors/deliver/processor_test.go (hunk 2 above)
Comment (Harwayne) [reply pkg/broker/handler/processors/deliver/processor_test.go:256]: Renamed it and added a description. I don't want to use `broker` in the name because this already generic for all CellTenants.

**Comment by Harwayne** [comment]
> @Harwayne: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-google-knative-gcp-conformance-tests	[f49fba5](https://github.com/google/knative-gcp/commit/f49fba51382f01a4bf63db6550c70a292c4e3017)	[link](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/google_knative-gcp/2107/pull-google-knative-gcp-conformance-tests/1355219993079320576)	`/test pull-google-knative-gcp-conformance-tests`
> [Full PR test history](https://gubernator.knative.dev/pr/google_knative-gcp/2107). [Your PR dashboard](https://gubernator.knative.dev/pr/Harwayne).

```
Message:MountVolume.SetUp failed for volume "default-token-lxzmb" : failed to sync secret cache: timed out waiting for the condition
```

/retest

**Comment by Harwayne** [comment]
```
MountVolume.SetUp failed for volume "default-token-qffpt" : failed to sync secret cache: timed out waiting for the condition
```

/retest

**Comment by Harwayne** [comment]
```
MountVolume.SetUp failed for volume "default-token-8ddw2" : failed to sync secret cache: timed out waiting for the condition
```

/retest

**Comment by Harwayne** [comment]
```
Error from server: error when creating "https://storage.googleapis.com/knative-nightly/net-istio/latest/net-istio.yaml": admission webhook "pilot.validation.istio.io" denied the request: unrecognized type PeerAuthentication
```

/retest
