### PR TITLE
added e2e test of gcp broker with four sources and fixed typo of docs

### LINKED ISSUE #639: E2E tests for GCP Broker with Sources
The existing E2E tests for the pubsub channel-based broker should be copied to use the new broker.

/area broker

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #639 

## Proposed Changes

- added e2e test of gcp broker with four sources
- refactored the duplicate code between gcp broker and broker with pubsub channel
- fixed typo of docs

### CODE REVIEW

**Comment by capri-xiyue** [comment]
Considering the size of the code review, I will separate https://github.com/google/knative-gcp/issues/639 with two PRs. One for GCP Broker with four sources and the other for GCP broker with [Broker flow to multiple triggers
](https://github.com/knative/eventing/blob/master/test/e2e/broker_channel_flow_test.go)

File: test/e2e/e2e_test.go [hunk 1]
```diff
@@ -313,3 +313,31 @@ func TestGCPBroker(t *testing.T) {
 	defer cancel()
 	GCPBrokerTestImpl(t, authConfig)
 }
+
+// TestCloudPubSubSourceWithGCPBroker tests we can knock a Knative Service from a GCPBroker from a CloudPubSubSource.
+func TestCloudPubSubSourceWithGCPBroker(t *testing.T) {
+	cancel := logstream.Start(t)
+	defer cancel()
```
Comment (ian-mi) [inline test/e2e/e2e_test.go:320]: Just `defer logstream.Start(t)`?

File: test/e2e/test_auditlogs.go [hunk 2]
```diff
@@ -48,15 +43,15 @@ func CloudAuditLogsSourceWithTestImpl(t *testing.T, authConfig lib.AuthConfig) {
 	defer lib.TearDown(client)
 
 	// Create a target Job to receive the events.
-	lib.MakeAuditLogsJobOrDie(client, methodName, project, resourceName, serviceName, targetName)
+	lib.MakeAuditLogsJobOrDie(client, lib.MethodName, project, resourceName, lib.ServiceName, targetName)
```
Comment (ian-mi) [inline test/e2e/test_auditlogs.go:46]: Should these still be arguments now that that constants have moved?

**Comment by ian-mi** [comment]
I would be reluctant to add an additional audit log test until #842 is fixed.

File: test/e2e/test_auditlogs.go (hunk 2 above)
Comment (capri-xiyue) [reply test/e2e/test_auditlogs.go:46]: I think it will be better if we still make these to be arguments so that callers can customize the AuditLogsJobs.

**Comment by capri-xiyue** [comment]
> I would be reluctant to add an additional audit log test until #842 is fixed.

I think we can add this test first and the later fix  [#842](https://github.com/google/knative-gcp/issues/842).  Considering we already enabled E2E for CloudAuditLogs and CloudAduditLogs for Broker with PubSub Channel. I don't think adding this one will increase much more flakiness.  
If we think CloudAuditLogs is really flaky, I think we should increase the priority of [#842](https://github.com/google/knative-gcp/issues/842)

File: test/e2e/e2e_test.go (hunk 1 above)
Comment (capri-xiyue) [reply test/e2e/e2e_test.go:320]: Does 
`cancel := logstream.Start(t)
 defer cancel()`
equal to 
`defer logstream.Start(t)`?

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go [hunk 3]
```diff
@@ -0,0 +1,331 @@
...
+	senderJob := resources.SenderJob(senderName, []v1.EnvVar{{
+		Name:  "BROKER_URL",
+		Value: brokerURL.String(),
+	}})
+	client.CreateJobOrFail(senderJob)
+
+	// Check if dummy CloudEvent is sent out.
+	if done := jobDone(client, senderName, t); !done {
+		t.Error("dummy event wasn't sent to broker")
+		t.Failed()
```
Comment (liu-cong) [inline test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:50]: Why call `t.Failed()`? I think it only returns true of false??

File: test/e2e/e2e_test.go [hunk 4]
```diff
@@ -313,3 +313,31 @@ func TestGCPBroker(t *testing.T) {
...
+	AuditLogsSourceBrokerWithGCPBrokerTestImpl(t, authConfig)
+}
+
+// TestCloudSchedulerSourceWithGCPBroker tests we can knock a Knative Service from a GCPBroker from a CloudSchedulerSource.
+func TestCloudSchedulerSourceWithGCPBroker(t *testing.T) {
+	cancel := logstream.Start(t)
+	defer cancel()
+	SchedulerSourceWithGCPBrokerTestImpl(t, authConfig)
+}
```
Comment (chizhg) [inline test/e2e/e2e_test.go:343]: Add one new line at the end of this file?

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go [hunk 5]
```diff
@@ -0,0 +1,331 @@
...
+		dummyTriggerName,
+		eventingtestresources.WithBroker(brokerName),
+		eventingtestresources.WithAttributesTriggerFilter(
+			eventingv1alpha1.TriggerAnyFilter, eventingv1alpha1.TriggerAnyFilter,
+			map[string]interface{}{"type": "e2e-testing-dummy"}),
+		eventingtestresources.WithSubscriberServiceRefForTrigger(kserviceName),
+	)
+}
+
+func createTriggerWithTargetServiceSubscriber(client *lib.Client, brokerName, targetName string) {
```
Comment (liu-cong) [inline test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:271]: I don't see the difference between `createTriggerWithTargetServiceSubscriber` and `createTriggerWithKServiceSubscriber`, except for the trigger name

Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:271]: How about `func reateTriggers(client *lib.Client, brokerName string, targets ...string)

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go [hunk 6]
```diff
@@ -0,0 +1,331 @@
...
+		eventingtestresources.WithAttributesTriggerFilter(
+			eventingv1alpha1.TriggerAnyFilter, eventingv1alpha1.TriggerAnyFilter,
+			map[string]interface{}{"type": "e2e-testing-resp"}),
+		eventingtestresources.WithSubscriberServiceRefForTrigger(targetName),
+	)
+}
+
+func createTriggersAndKService(client *lib.Client, brokerName, targetName string) {
+	// Create the Knative Service.
+	kserviceName := CreateKService(client)
```
Comment (liu-cong) [inline test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:285]: Let's move this out for consistency - the targetName is created outside of this function. Let's make this function only create triggers, not target services

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go [hunk 7]
```diff
@@ -0,0 +1,331 @@
...
+	// Create the Knative Service.
+	kservice := resources.ReceiverKService(
+		kserviceName, client.Namespace)
+	client.CreateUnstructuredObjOrFail(kservice)
+	return kserviceName
+
+}
+
+func createTriggerWithKServiceSubscriber(client *lib.Client, brokerName, kserviceName string) {
+	dummyTriggerName := "dummy-broker-" + brokerName
```
Comment (liu-cong) [inline test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:260]: This trigger is not "dummy", maybe just call it kserviceTrigger

File: test/e2e/lib/auditlogs.go [hunk 8]
```diff
@@ -25,6 +25,11 @@ import (
 	v1 "k8s.io/api/core/v1"
 )
 
+const (
```
Comment (chizhg) [inline test/e2e/lib/auditlogs.go:28]: Are the two constant only used by the auditlogs test? If yes maybe it would be better to move them out of this package, or rename them to be less confusing?

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go [hunk 9]
```diff
@@ -0,0 +1,331 @@
...
+	var url apis.URL = apis.URL(brokerURL)
+	// Just to make sure all resources are ready.
+	time.Sleep(5 * time.Second)
+
+	// Create the CloudSchedulerSource.
+	lib.MakeSchedulerOrDie(client, sName, data, targetName, authConfig.PubsubServiceAccount,
+		kngcptesting.WithCloudSchedulerSourceSinkURI(&url),
+	)
+
+	msg, err := client.WaitUntilJobDone(client.Namespace, targetName)
```
Comment (liu-cong) [inline test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:218]: use `jobDone`?

File: test/e2e/lib/auditlogs.go (hunk 8 above)
Comment (capri-xiyue) [reply test/e2e/lib/auditlogs.go:28]: These two constants are used both in CloudAuditLogsSourceWithTestImpl of test/e2e/test_auditlogs.go and BrokerEventTransformationTestWithAuditLogsSourceHelper of test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go. I moved it here to avoid cycle import. I will rename them to be less confusing.

File: test/e2e/test_auditlogs.go [hunk 10]
```diff
@@ -31,11 +31,6 @@ import (
 	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
 )
 
-const (
```
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/test_auditlogs.go:34]: These two constants are used both in CloudAuditLogsSourceWithTestImpl of test/e2e/test_auditlogs.go and BrokerEventTransformationTestWithAuditLogsSourceHelper of test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go.  I move these two constants to libs because clients use the same args.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go [hunk 11]
```diff
@@ -0,0 +1,331 @@
+package helpers
+
+import (
```
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:3]: I followed the naming convention in eventing. For example: https://github.com/knative/eventing/blob/master/test/e2e/helpers/broker_event_transformation_test_helper.go

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go [hunk 12]
```diff
@@ -0,0 +1,331 @@
...
+func jobDone(client *lib.Client, podName string, t *testing.T) bool {
+	msg, err := client.WaitUntilJobDone(client.Namespace, podName)
+	if err != nil {
+		t.Error(err)
+		return false
+	}
+	if msg == "" {
+		t.Error("No terminating message from the pod")
+		return false
+	} else {
```
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:315]: Why we don't need the `else` here? I'm kind of confused.

[the remark this answers is not in the document]
Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:315]: there is a `return` in `if`

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 3 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:50]: I refactored the code. This is what we used to use https://github.com/google/knative-gcp/blob/bb7cfe32ebeb07932f0143a1a7a4092dd218195a/test/e2e/test_broker_pubsub.go#L88. I thought when the tests fail, we will use t.Failed to mark `Fail` for this test case.

Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:50]: t.Failed() does not mark the test to fail, it only return the status.

t.Error already marks the test fail.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 5 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:271]: The extensions are also different. One use map[string]interface{}{"type": "e2e-testing-dummy"}) and the other use map[string]interface{}{"type": "e2e-testing-resp"}). 
Most of the code are already refactored into the function 
`func (client *Client) CreateTriggerOrFail(name string, options ...resources.TriggerOption) *v1alpha1.Trigger `

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 6 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:285]: This function is used for all GCP Broker with different sources. That's why we move it here.
We already have specific function for creating triggers.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 7 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:260]: I thought we call it dummy because it doesn't filter anything and it's used for the dummy event. That's the naming convention for both knative-eventing and knative-gcp

File: docs/examples/cloudschedulersource/README.md [hunk 13]
```diff
@@ -17,7 +17,7 @@ scheduled events from
    [`CloudSchedulerSource`](cloudschedulersource.yaml)
 
    ```shell
-   export APP_ENGINE_LOCATION=us-central1
+   export APP_ENGINE_LOCATION=us-central
    gcloud app create --region=$APP_ENGINE_LOCATION
```
Comment (bskaplan) [inline docs/examples/cloudschedulersource/README.md:21]: Does app engine accept us-central1 as the region? App Engine calls it us-central.

File: test/e2e/test_gcp_broker.go [hunk 14]
```diff
@@ -51,83 +48,60 @@ Note: the number denotes the sequence of the event that flows in this test case.
 */
 
 func GCPBrokerTestImpl(t *testing.T, authConfig lib.AuthConfig) {
```
Comment (bskaplan) [inline test/e2e/test_gcp_broker.go:50]: FYI, this may have a small conflict with #1022 which adds the same metrics-checking logic to this test impl as is in the broker_pubsub test.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 7 above)
Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:260]: we do not need to follow those. I would either rename it or add a comment, the name is really misleading

File: test/e2e/e2e_test.go (hunk 1 above)
Comment (ian-mi) [reply test/e2e/e2e_test.go:320]: Ah, I misread this.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 6 above)
Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:285]: Then I don't think we need this function. I would just inline CreateKService and CreateTrigger

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:3]: let at least get rid of the `helper` in the file, it's already in `helper` package

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 5 above)
Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:271]: You can save some duplicated code by doing`func reateTrigger(client *lib.Client, brokerName, triggerName, extensions)`, or just inline client.Core.CreateTriggerOrFail. But up to you.

File: test/e2e/test_gcp_broker.go (hunk 14 above)
Comment (capri-xiyue) [reply test/e2e/test_gcp_broker.go:50]: Yep. There will be a conflict since this PR did a refactor of the duplicate code between GCP Broker and Broker with PubSub Channel. But I think that should be quite fast to resolve the conflicts.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:3]: ok

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:315]: Thanks for the clarification. I missed the `return` above.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 3 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:50]: `t.Error()` use `c.Fail()` but `t.Failed()` call `c.Failed()`. I think previous we use t.Failed to mark failed reports and stops the execution.
// Fail marks the function as having failed but continues execution.
func (c *common) Fail() {
	if c.parent != nil {
		c.parent.Fail()
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	// c.done needs to be locked to synchronize checks to c.done in parent tests.
	if c.done {
		panic("Fail in goroutine after " + c.name + " has completed")
	}
	c.failed = true
}

// Failed reports whether the function has failed.
func (c *common) Failed() bool {
	c.mu.RLock()
	failed := c.failed
	c.mu.RUnlock()
	return failed || c.raceErrors+race.Errors() > 0
}

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 6 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:285]: If we don't have this function, all test cases will need to inline these 5 codes. That's why I change it to one function. For the above comments, I did't create anotherfunc createTrigger(client *lib.Client, brokerName, triggerName, extensions) is because this function will end up calling just one line 
`client.Core.CreateTriggerOrFail(
                 triggerName,
		eventingtestresources.WithBroker(brokerName),
		eventingtestresources.WithAttributesTriggerFilter(
			eventingv1alpha1.TriggerAnyFilter, eventingv1alpha1.TriggerAnyFilter,
			map[string]interface{}{"type": "e2e-testing-resp"}),
		eventingtestresources.WithSubscriberServiceRefForTrigger(targetName),
	)`

File: docs/examples/cloudschedulersource/README.md (hunk 13 above)
Comment (capri-xiyue) [reply docs/examples/cloudschedulersource/README.md:21]: No, app engine doesn't accept us-central1 as the region.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 7 above)
Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go:260]: I will rename it.

File: test/e2e/test_gcp_broker.go (hunk 14 above)
Comment (capri-xiyue) [reply test/e2e/test_gcp_broker.go]: I solved the merge conflicts. But you may need to add more metrics-checking for the new E2E tests added in this PR once this PR got merged.

File: test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go (hunk 6 above)
Comment (liu-cong) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go]: My main point about this one is it's unclear to me what it does but reading its name. I feel better if the KService is created outside of this function, and this is changed to `createTriggersForKserviceAndTargetService`...

But I would'd say this is a blocker.

Comment (capri-xiyue) [reply test/e2e/lib/helpers/broker_event_transformation_test_with_source_helper.go]: I will change the naming  to `createTriggersForKserviceAndTargetService`

**Comment by capri-xiyue** [comment]
The wi tests are quite flaky. I tested in my local with single test case, it is not that flaky.  It looks like running all E2E tests together increase the flakiness . But when it fails because of the error of cre-pull instead of anything related to gcp-broker:
"error":"unable to create sunscription \"cre-pull-99b0ac99-9d81-44a9-b340-236b4c917490\", rpc error: code = Unauthenticated desc = transport: compute: Received 403 \nUnable to generate token; IAM returned 403 Forbidden: The caller does not have permission\n\nThis error could be caused by a missing IAM policy binding on the target IAM service account.\n\nYou can create the necessary policy binding with:\n\n gcloud iam service-accounts add-iam-policy-binding \\\n --role=roles/iam.workloadIdentityUser \\\n --member=\"serviceAccount:xiyue-opensource-project-wi.svc.id.goog[test-cloud-storage-source-with-g-c-p-broker-s7xxf/cre-pubsub]\" \\\n cre-pubsub@xiyue-opensource-project-wi.iam.gserviceaccount.com\n\nFor more information, refer to the Workload Identity documentation:\n\n https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity\n\n","stacktrace":"main.main\n\tgithub.com/google/knative-gcp/cmd/pubsub/receive_adapter/main.go:93\nruntime.main\n\truntime/proc.go:203"}

**Comment by capri-xiyue** [comment]
This pull-google-knative-gcp-integration-tests is also flaky. It's flaky mainly because of CloudAuditLogsSource and CloudStorageSource.

**Comment by grac3gao** [comment]
Checked with failure log, looks like integration test and wi test are all becoming more flaky. We have flaky tests: AuditLogSource, AuditLogSourceWithPubSubChannel, StorageSourceWithPubSubChannel. As GCP broker shares the same function as PubSubChannel Broker, we have two more flaky tests: AuditLogSourceWithGCPBroker, StorageSourceWithGCPBroker for each e2e tests now, this generally increases both e2e tests flakiness. 

A known issue for Workload Identity is WI has delay in receive-adapter: https://github.com/google/knative-gcp/issues/759. According to the error message, it seems that the receive-adapter is still in that delay recovering period, and the test is timeout. This further increases the flakiness in wi tests.
